services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:7070

  db:
    image: supabase/postgres
    restart: unless-stopped
    container_name: pro-idea-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - POSTGRES_PORT=5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  postgres:
